name: Pull Request Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 9.9.0
      uses: actions/setup-node@v1
      with:
        node-version: 9.9.0
    - name: Install dependencies
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm install
    - name: Build application
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        npm run prepublish
